### ISSUE TITLE
Világos mód bug

### ISSUE THREAD

**Issue by Maho-Yoshino** [refilc/naplo#113]
![Screenshot_20240507_144934.jpg](https://github.com/refilc/naplo/assets/62778359/07bb4bf1-2e63-47d9-aed7-0f0deb107c6d)
![Screenshot_20240507_145020.jpg](https://github.com/refilc/naplo/assets/62778359/8e0752d6-36ea-4bb1-b1be-554b3f97e708)

v5.0.0
Samsung dev beállításokban nincs a force dark mode bekapcsolva

**Comment by kimaah** [comment]
settings -> szemelyre szabas -> szinek -> default kekre nyomj hogy visszaallitson mindent normalisra es tobbet nem lesz ilyen gond
