### ISSUE TITLE
"There was a problem while parsing the package" frissítéskor

### ISSUE THREAD

**Issue by Maho-Yoshino** [refilc/naplo#129]
![Screenshot_20240819_094004_Package installer.jpg](https://github.com/user-attachments/assets/ae1d20cf-b9dc-4916-a9ea-708ec68d9a6d)

Ez a hiba jelenik meg amikor próbálok v5.0.4re frissíteni (v5.0.3ról)

**Comment by balint1414** [comment]
Probáld meg letörölni az appot, és úgy feltelepíteni.

**Comment by Maho-Yoshino** [comment]
> Probáld meg letörölni az appot, és úgy feltelepíteni.

Működött, köszi
