### ISSUE TITLE
Az 5-ös streak tűz ikonja bugol.

### ISSUE THREAD

**Issue by nikkeisadev** [refilc/naplo#136]
Hali! A kövi hibát találtam: amikor megnyitom a profilomat, és van streakem, a tűz ikon valamiért elcsúszik és megjelenik két sárga vonal. Gyanítom hogy Flutter Debug lehet, de pontosan nem tudom.

**Comment by PPearoo** [comment]
zárva, [ismert](https://discord.com/channels/1111649116020285532/1112696376447483967/1112696745982439534)
