### ISSUE TITLE
Profilkép hiba

### ISSUE THREAD

**Issue by efi99** [refilc/naplo#14]
Több felhasználó esetében, a ki nem választott felhasználók profilképeként a kiválasztott felhasználó kezdőbetűje jelenik meg (vagyis mindenkinek ugyanaz), nem a sajátja. Ez még akkor is így történik, ha egyébként a kiválasztott felhasználónak profilkép is van beállítva (ekkor felül ugyan a profilkép lesz, de alul a helyzet változatlanul az ő kezdőbetűje mindenkinél)
![Screenshot_20230610_194356](https://github.com/refilc/naplo/assets/62113872/29a14f92-3df2-4f0f-aff6-754ab557a853)

**Comment by kimaah** [comment]
javitom is, koszi

**Comment by kimaah** [comment]
fixed
