### ISSUE TITLE
Nem konzisztens formázás a tantárgyak nevein a widgeten.

### ISSUE THREAD

**Issue by ubionexd** [refilc/naplo#16]
![Screenshot_2023-06-10-22-54-03-489_com.miui.home-edit.jpg](https://github.com/refilc/naplo/assets/70473378/39d4723e-38e5-436a-8510-2c851ebdd161)

A formázás az alkalmazásban helyes, csak a widgeten nem.

---

Redmi Note 10 Pro
Android 13 + MIUI 14.0.3

**Comment by PearooXD** [comment]
Ez még releváns?

**Comment by ubionexd** [comment]
Nem tudom, mivel a KRÉTA nekem most valamiért nem működik és eltűntette az órarendem.

**Comment by PearooXD** [comment]
Mert a KRÉTA egy fasz és egyszerre csak egy kliensről engedi bejelentkezni a felhasználót.

Webes felületen be tudsz jelentkezni, ott meg tudod nézni?
