### ISSUE TITLE
Helytelen Felhasználónév/Jelszó

### ISSUE THREAD

**Issue by Zsobix** [refilc/naplo#26]
![tmp-1688047232527](https://github.com/refilc/naplo/assets/45757909/24a2ec89-668c-43c2-b15f-575eb2cf7fb4)

Xiaomi Redmi 9AT
Android 13.1: ArrowOS AOSP

Többször is lecsekkoltam de még mindig nem működik.
reFilc verzió: v4.1.1-beta

**Comment by Zsobix** [comment]
Megcsináltam!
Az AOSP Mods appal betudtam kapcsolni az "App Downgrade-et"
és utána meg tudtam telepíteni.

**Comment by Zsobix** [comment]
oops
megtudtam valamennyire csinálni de még mindig nem mükszik.

**Comment by kimaah** [comment]
probalj 1-2 space-t (szokoz) irni a neved moge, az altalaban megoldja a problemat, engem is csak igy enged be

**Comment by Zsobix** [comment]
Köszönöm! Működött.

**Comment by zalnaRs** [comment]
Nekem most se megy, a sima kréta se csak a webes.
A szülői se ment, de megvaltoztattam a jelszót is aztán már jó lett

**Comment by sharkmu** [comment]
@zalnaRs krétánál van a hiba.
