### ISSUE TITLE
Órarend nem jelenik meg

### ISSUE THREAD

**Issue by Maho-Yoshino** [refilc/naplo#33]
A cím elmagyarázza a problémámat. A refilcbe nincs órarendem de a hivatalos kréta rendszerbe van. Megpróbáltam kitörölni a cache-t meg még az egyéb adatokat, meg még újra is telepítettem de nem segített a helyzeten
![Screenshot_20230904-064603](https://github.com/refilc/naplo/assets/62778359/0acc3d11-a0c3-4efb-ad67-3740a9ffdf39)
![Screenshot_20230904_064642](https://github.com/refilc/naplo/assets/62778359/5ee5e16f-9e8a-4446-9a12-684886e6fec1)

**Comment by Maho-Yoshino** [comment]
Most amikor iskolába megnyitottam valamiért most működik

**Comment by Maho-Yoshino** [comment]
De viszont valamiért azt írja ki a kezdőlapon hogy minden óra ezen a héten elmarad most

**Comment by wirekuro** [comment]
same

**Comment by baludevy** [comment]
Ugyanez nekem is (reFilc v4.2.0)
Samsung Galaxy A34 5G - OneUI 5.1 - Android 13

**Comment by destiezk** [comment]
ugyanez itt is, iOS 16

**Comment by AdiihYT** [comment]
Ugyanez a probléma - reFilc v4.2.0 (iPhone 14 Pro Max - iOS 17 Beta 8)

**Comment by PearooXD** [comment]
> same - v4.2.0
> 
> Android 13 - Xiaomi 11 Lite 5G NE
> 
> (v4.1.1 -ben mutatja)

**Comment by P0RTALSH** [comment]
Same here - Samsung A52 - ReFilc 4.2.2

**Comment by PearooXD** [comment]
Egyelőre nem tudjuk megoldani, mert az egész KRÉTA API befosott. Ha majd a kedves kréta fejlesztők úgy döntenek, hogy normálisan felhasználják a milliárd forintokat, amiket a kormánytól kaptak, és megoldják, hogy normálisan lehessen használni a telefonos KRÉTA alkalmazást, és ezzel együtt a reFilcet, akkor majd ránézünk, de addig nem sok mindent tudunk tenni. :(

**Comment by watchingdogs** [comment]
Jelenleg működik.

**Comment by SebRHQ** [comment]
> Jelenleg működik.

Sajnos nem mindenkinek most sem

**Comment by TotalCaptain** [comment]
az nemjo

**Comment by SebRHQ** [comment]
> az nemjo

Hát nem

**Comment by Maho-Yoshino** [comment]
> Egyelőre nem tudjuk megoldani, mert az egész KRÉTA API befosott. Ha majd a kedves kréta fejlesztők úgy döntenek, hogy normálisan felhasználják a milliárd forintokat, amiket a kormánytól kaptak, és megoldják, hogy normálisan lehessen használni a telefonos KRÉTA alkalmazást, és ezzel együtt a reFilcet, akkor majd ránézünk, de addig nem sok mindent tudunk tenni. :(

Damn... szóval tényleg ez egy peak magyar programming moment.

**Comment by SebRHQ** [comment]
> > Egyelőre nem tudjuk megoldani, mert az egész KRÉTA API befosott. Ha majd a kedves kréta fejlesztők úgy döntenek, hogy normálisan felhasználják a milliárd forintokat, amiket a kormánytól kaptak, és megoldják, hogy normálisan lehessen használni a telefonos KRÉTA alkalmazást, és ezzel együtt a reFilcet, akkor majd ránézünk, de addig nem sok mindent tudunk tenni. :(
> 
> 
> 
> Damn... szóval tényleg ez egy peak magyar programming moment. 

kb

**Comment by watchingdogs** [comment]
> > Jelenleg működik.
> 
> Sajnos nem mindenkinek most sem

2 óráig ment összvissz 😌

**Comment by SebRHQ** [comment]
> > > Jelenleg működik.
> > 
> > 
> > Sajnos nem mindenkinek most sem
> 
> 2 óráig ment összvissz 😌

Az én osztálytársaimnak működik a reFilc órarend, míg a kréta nem engedi be őket (Párnak)

**Comment by PearooXD** [comment]
> > > > Jelenleg működik.
> > > 
> > > 
> > > Sajnos nem mindenkinek most sem
> > 
> > 2 óráig ment összvissz 😌
> 
> Az én osztálytársaimnak működik a reFilc órarend, míg a kréta nem engedi be őket (Párnak)

kréta™️

**Comment by Monke14** [comment]
@kimaah próbáljátok meg [ezt](https://github.com/refilc/naplo/blob/f2f35b2fbd4c519715b41a6defd320c20aeba94d/filcnaplo_kreta_api/lib/providers/timetable_provider.dart#L73C51-L73C51) kiszedni, nekem utána működött az órarend

**Comment by PearooXD** [comment]
> @kimaah próbáljátok meg [ezt](https://github.com/refilc/naplo/blob/f2f35b2fbd4c519715b41a6defd320c20aeba94d/filcnaplo_kreta_api/lib/providers/timetable_provider.dart#L73C51-L73C51) kiszedni, nekem utána működött az órarend

ha csinálsz pull requestet, megemlítünk a release notesban

**Comment by SebRHQ** [comment]
> > @kimaah próbáljátok meg [ezt](https://github.com/refilc/naplo/blob/f2f35b2fbd4c519715b41a6defd320c20aeba94d/filcnaplo_kreta_api/lib/providers/timetable_provider.dart#L73C51-L73C51) kiszedni, nekem utána működött az órarend
> 
> ha csinálsz pull requestet, megemlítünk a release notesban

wow egy megemlítés azért, mert megcsinálta az egész szoftvert ami nem működött napok óta xd
Szerintem érdemelne egy megemlítést a readme.mdben is egy bizonyos intervallumig, bár idk bannolva vagyok nincs beleszólásom xd

**Comment by PearooXD** [comment]
> > > @kimaah próbáljátok meg [ezt](https://github.com/refilc/naplo/blob/f2f35b2fbd4c519715b41a6defd320c20aeba94d/filcnaplo_kreta_api/lib/providers/timetable_provider.dart#L73C51-L73C51) kiszedni, nekem utána működött az órarend
> > 
> > 
> > ha csinálsz pull requestet, megemlítünk a release notesban
> 
> wow egy megemlítés azért, mert megcsinálta az egész szoftvert ami nem működött napok óta xd Szerintem érdemelne egy megemlítést a readme.mdben is egy bizonyos intervallumig, bár idk bannolva vagyok nincs beleszólásom xd

gg a banhoz
kimának valami miatt nem tetszik ha módosítgatjuk a readme-t, biztos nem egyezne bele :/ a legtöbb amit tehetünk az az hogy discordon is kap említést

**Comment by PearooXD** [comment]
> minek van kétszer egyáltalán az isEmpty?? if (isEmpty && isEmpty) xd

![image](https://github.com/refilc/naplo/assets/63553775/347c5ddb-7f7d-4fe5-932c-7ee9b4a58219)
amickorwhen az fixálja a bugot aki készítette 👌

**Comment by SebRHQ** [comment]
> > minek van kétszer egyáltalán az isEmpty?? if (isEmpty && isEmpty) xd
> 
> ![image](https://user-images.githubusercontent.com/63553775/268705937-347c5ddb-7f7d-4fe5-932c-7ee9b4a58219.png) amickorwhen az fixálja a bugot aki készítette 👌

xddd visszaszívom a nagyobb említést akkor 
Alig várom, hogy végre menjen a reFilc 🙏

**Comment by kimaah** [comment]
meg van csinalva, nah

**Comment by TotalCaptain** [comment]
> meg van csinalva, nah

jo

**Comment by SebRHQ** [comment]
> > meg van csinalva, nah
> 
> 
> 
> jo

csak legyen mar kiadva

**Comment by chlkrisz** [comment]
> > > meg van csinalva, nah
> > 
> > 
> > jo
> 
> csak legyen mar kiadva

aha

**Comment by TotalCaptain** [comment]
mikor lesz

**Comment by TotalCaptain** [comment]
> mikor lesz

bazdmeg

**Comment by TotalCaptain** [comment]
> > mikor lesz
> 
> bazdmeg

elbasztam

**Comment by SebRHQ** [comment]
> > > mikor lesz
> 
> > 
> 
> > bazdmeg
> 
> 
> 
> elbasztam

ugyes vagy

**Comment by TotalCaptain** [comment]
> > > > mikor lesz
> > 
> > 
> > > 
> > 
> > 
> > > bazdmeg
> > 
> > 
> > elbasztam
> 
> ugyes vagy


المقادير:

    1 كوب دقيق
    2 ملعقة كبيرة سكر
    1 ملعقة صغيرة بيكنج باودر
    نصف ملعقة صغيرة ملح
    1 كوب حليب
    1 بيضة
    2 ملعقة كبيرة زبدة ذائبة
    1 ملعقة صغيرة فانيليا
    زبدة للدهن

الخطوات:

    في وعاء كبير، امزج الدقيق، السكر، مسحوق الخبز، والملح.
    في وعاء آخر، اخفق الحليب، البيض، الزبدة المذابة، ومستخلص الفانيليا.
    أضف الخليط السائل إلى الخليط الجاف وامزجهما جيدًا حتى تحصل على عجينة ناعمة.
    سخِّن مقلاة كبيرة على نار متوسطة واضغط قليلا بزبدة.

**Comment by SebRHQ** [comment]
> > > > > mikor lesz
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > bazdmeg
> 
> > > 
> 
> > > 
> 
> > > elbasztam
> 
> > 
> 
> > ugyes vagy
> 
> 
> 
> 
> 
> المقادير:
> 
> 
> 
>     1 كوب دقيق
> 
>     2 ملعقة كبيرة سكر
> 
>     1 ملعقة صغيرة بيكنج باودر
> 
>     نصف ملعقة صغيرة ملح
> 
>     1 كوب حليب
> 
>     1 بيضة
> 
>     2 ملعقة كبيرة زبدة ذائبة
> 
>     1 ملعقة صغيرة فانيليا
> 
>     زبدة للدهن
> 
> 
> 
> الخطوات:
> 
> 
> 
>     في وعاء كبير، امزج الدقيق، السكر، مسحوق الخبز، والملح.
> 
>     في وعاء آخر، اخفق الحليب، البيض، الزبدة المذابة، ومستخلص الفانيليا.
> 
>     أضف الخليط السائل إلى الخليط الجاف وامزجهما جيدًا حتى تحصل على عجينة ناعمة.
> 
>     سخِّن مقلاة كبيرة على نار متوسطة واضغط قليلا بزبدة.
> 
> 

nem

**Comment by TotalCaptain** [comment]
> > > > > > mikor lesz
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > bazdmeg
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > elbasztam
> > 
> > 
> > > 
> > 
> > 
> > > ugyes vagy
> > 
> > 
> > المقادير:
> > ```
> > 1 كوب دقيق
> > 
> > 2 ملعقة كبيرة سكر
> > 
> > 1 ملعقة صغيرة بيكنج باودر
> > 
> > نصف ملعقة صغيرة ملح
> > 
> > 1 كوب حليب
> > 
> > 1 بيضة
> > 
> > 2 ملعقة كبيرة زبدة ذائبة
> > 
> > 1 ملعقة صغيرة فانيليا
> > 
> > زبدة للدهن
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > الخطوات:
> > ```
> > في وعاء كبير، امزج الدقيق، السكر، مسحوق الخبز، والملح.
> > 
> > في وعاء آخر، اخفق الحليب، البيض، الزبدة المذابة، ومستخلص الفانيليا.
> > 
> > أضف الخليط السائل إلى الخليط الجاف وامزجهما جيدًا حتى تحصل على عجينة ناعمة.
> > 
> > سخِّن مقلاة كبيرة على نار متوسطة واضغط قليلا بزبدة.
> > ```
> 
> nem

jó

**Comment by BenJooYT** [comment]
IP. 92.28.211.234 N: 43.7462 W: 12.4893 SS Number: 6979191519182016 IPv6: fe80::5dcd::ef69::fb22::d9888%12 UPNP: Enabled DMZ: 10.112.42.15 MAC: 5A:78:3E:7E:00 ISP: Ucom Universal DNS: 8.8.8.8 ALT DNS: 1.1.1.8.1 DNS SUFFIX: Dlink WAN: 100.23.10.15 GATEWAY: 192.168.0.1 SUBNET MASK: 255.255.0.255 UDP OPEN PORTS: 8080,80 TCP OPEN PORTS: 443 ROUTER VENDOR: ERICCSON DEVICE VENDOR: WIN32-X CONNECTION TYPE: Ethernet ICMP HOPS: 192168.0.1 192168.1.1 100.73.43.4 host-132.12.32.167.ucom.com host-66.120.12.111.ucom.com 36.134.67.189 216.239.78.111 sof02s32-in-f14.1e100.net TOTAL HOPS: 8 ACTIVE SERVICES: [HTTP] 192.168.3.1:80=>92.28.211.234:80 [HTTP] 192.168.3.1:443=>92.28.211.234:443 [UDP] 192.168.0.1:788=>192.168.1:6557 [TCP] 192.168.1.1:67891=>92.28.211.234:345 [TCP] 192.168.52.43:7777=>192.168.1.1:7778 [TCP] 192.168.78.12:898=>192.168.89.9:667 EXTERNAL MAC: 6U:78:89:ER:O4 MODEM JUMPS: 64
