### ISSUE TITLE
Sikertelen frissítés

### ISSUE THREAD

**Issue by ubionexd** [refilc/naplo#4]
Az APK letöltése és telepítése után úgy tűnik, mintha az egyel régebbi verzió települt volna és a frissítések sikertelenek az alkalmazáson belül.

---

A hiba így jön létre nekem:
1. reFilc 4.0.2 APK letöltése a weboldalról (GitHub Releases-ből is próbáltam, vége ugyan az)
2. APK feltelepítése
3. Alkalmazás megnyitása: A beállításokban a verziószám 4.0.1 és a telefon beállításaiban is ezt írja
4. Feldobja hogy frissítés elérhető, rányomok, letöltés
5. Alul vörös hiba dobozban feldobja hogy frissítés telepítése sikertelen

---

Rendszer:
Redmi Note 10 Pro
Android 13 + MIUI 14.0.3

**Comment by kimaah** [comment]
Köszönjük a jelentést, a probléma javítva lett! A frissített APK ezen a [link](https://github.com/refilc/naplo/releases/download/4.0.2/refilc-v4.0.2.apk)-en tölthető le. (refilc/naplo/releases/tag/4.0.2)

**Comment by kimaah** [comment]
Köszönjük a jelentést, a probléma javítva lett! A frissített APK ezen a [link](https://github.com/refilc/naplo/releases/download/4.0.2/refilc-v4.0.2.apk)-en tölthető le. (refilc/naplo/releases/tag/4.0.2)
