### ISSUE TITLE
Widget bejelentkezés képernyő a régi brand

### ISSUE THREAD

**Issue by ubionexd** [refilc/naplo#57]
Amikor kijelentkezel a reFilcből, a widget kijelez egy kijelzőt, hogy jelentkezz be, viszont ez a kijelző nem reFilces, hanem a régi, zöld Filces ikont és színeket tartalmazza.
![Screenshot_2023-09-21-08-43-47-056_com.miui.home-edit.jpg](https://github.com/refilc/naplo/assets/70473378/2f9591a3-e44b-49cc-8703-0d183f9b5911)

**Comment by ReinerRego** [comment]
Kövi verzió fix
