### ISSUE TITLE
Eltér a "programozás" tantárgy ikonja a főoldalon és a jegyek fülön.

### ISSUE THREAD

**Issue by vb2007** [refilc/naplo#71]
![Screenshot_2023-10-10-09-58-04-998_hu.refilc.naplo-edit.jpg](https://github.com/refilc/naplo/assets/68242928/b9df25f0-0d9a-440c-8191-a9e7849d90a9)

![Screenshot_2023-10-10-09-58-22-839_hu.refilc.naplo-edit.jpg](https://github.com/refilc/naplo/assets/68242928/beeb9b4b-eb17-4663-b0db-1501f3beafdb)

A jegyek menüben rossz ikon jelenik meg.

**Comment by PearooXD** [comment]
nem hinném. a refilc a tanóra neve alapján állítja be az ikont, lehet hogy konfliktál a két ikonpakk

**Comment by vb2007** [comment]
Igaz is. Ezek szerint valamiért a szerencsétlen Kréta szervereken 2 tantárgy van 2 különböző névvel. Az egyikkel bejelentenek, másikkal értékelnek...
