### ISSUE TITLE
Nem lehet bejelentkezni

### ISSUE THREAD

**Issue by tatarmb4s** [refilc/naplo#77]
Galaxy A40-en Android 11 alatt nem tudok bejelentkezni. A legújabb (4.4) verzió a jó om-re és jelszóra azt írja, hogy hibás. Mondjuk a kréta is ugyanevvel a hibával küzd épp. Webes kréta evvel a jelszóval és felhasználónévvel beenged.

A régi 3.5.3-as filc furcsa de működik, akkor amikor épp nincs kifagyás rohama (megnyitom majd becsukja magát, akkor kezdődött amikor egyedi profilképet állítottam be benne).

**Comment by PearooXD** [comment]
Tudunk róla, Krétánál van a probléma és nem tudjuk elérni a régi filces kódot specifically.

Discord szerveren /tag login
