### ISSUE TITLE
zart kepernyonel is megnyitva marad az app (Android)

### ISSUE THREAD

**Issue by vinnie0612** [refilc/naplo#78]
Hali, Galaxy A54 eszkozon meg active screen lockkal is (le van zarva a kepernyo) "megnyitva marad" az app, teljesen hasznalhato a UI, barmit meg lehet nezni. ha kilepek belole rendesen keri az ujjlenyomatot/pin kodot. eleg fura issue es szerintem eleg nagy security risk

**Comment by ReinerRego** [comment]
Hali, elvben ez egy funkció, van egy flag hozzá androidon. Kövi frissítésben megcsináljuk kapcsolhatóvá

**Comment by kimaah** [comment]
fixed (ki lett veve ideiglenesen)
