### ISSUE TITLE
0. óra teljes órarend nézetben

### ISSUE THREAD

**Issue by kszkristof** [refilc/naplo#85]
Ha a teljes órarendet szeretném látni (fektetett nézetben) akkor csak 1. órától mutatja az órákat az app (0. óra hiányzik). 

Példa:
[fektetett módban hiányzik](https://github.com/refilc/naplo/assets/64156310/6b2ca0d1-6cb1-43e5-86dd-645c5ce21bef)
[álló módban helyén van](https://github.com/refilc/naplo/assets/64156310/1dddaa3c-0cf7-4c9a-acf0-926286dfa52a)

Megpróbálhatom ezt én is kijavítani mert valamennyire konyítok a flutterhez de nem ígérek semmit

**Comment by kimaah** [comment]
megoldva, v5.0-ban erkezik <3
